### ISSUE TITLE
docker stats displays the total memory available on the host instead of the requested limit

### ISSUE THREAD

**Issue by sestegra** [nestybox/sysbox#303] opened 2021-05-29 23:49 UTC
If the maximum amount of memory that the container can use is set, then `sysbox` follows the given limitations.
Nevertheless, `docker stats` displays the total memory available on the host instead of the requested limit.

In my case, 32 GB total are available and 8 GB are set as the limit.
```
$ docker --version
Docker version 20.10.6, build 370c289

$ sysbox-runc --version
sysbox-runc
	edition: 	Community Edition (CE)
	version: 	0.3.0
	commit: 	df952e5276cb6e705e0be331e9a9fe88f372eab8
	built at: 	Sat Mar 27 01:34:12 UTC 2021
	built by: 	Rodny Molina
	oci-specs: 	1.0.2-dev

$ cat /proc/meminfo | grep MemTotal
MemTotal:       32860060 kB

$ docker exec syscont cat /sys/fs/cgroup/memory/memory.memsw.max_usage_in_bytes
8589504512

$ docker stat
CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
1b424980eda3   syscont         3.95%     5.478GiB / 31.34GiB   17.48%    71.6MB / 152MB    10.5MB / 8.19kB   470
```

**Comment by ctalledo** [comment] 2021-05-30 01:03
Hi @sestegra ,

Thanks for discovering this, we were not aware of it.

I can confirm that with the OCI runc, `docker stats` reports the appropriate mem limits:

```
docker run -d --rm -m=128m alpine tail -f /dev/null

docker stats --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O      BLOCK I/O   PIDS
ed11614d90cf   quirky_lewin   0.01%     764KiB / 128MiB     0.58%     2.7kB / 0B   0B / 0B     1
```

The "MEM LIMIT" is 128 MiB as expected.

However, with Sysbox runc it reports the incorrect limit (even though the container is in fact limited via cgroups):

```
$ docker run --runtime=sysbox-runc -d --rm -m=128m alpine tail -f /dev/null

$ docker stats --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O      BLOCK I/O   PIDS
e6001f4a9091   heuristic_wu   0.01%     520KiB / 3.843GiB   0.01%     2.6kB / 0B   0B / 0B     1
```

The "MEM LIMIT" is incorrectly displayed as 3.84GiB (the host's mem), even though the container is limited to 128 MiB.

I'll investigate how `docker stats` is gathering the mem limit info to figure out why it's not displayed properly with sysbox-runc.

**Comment by ctalledo** [comment] 2021-05-30 01:17
On a quick look , it seems the problem is the following: when docker creates a container, it creates a cgroup subtree for it (e.g., `/sys/fs/cgroup/docker/<container-id>`. Sysbox then creates a subtree under this cgroup (e.g.,  `/sys/fs/cgroup/docker/<container-id>/syscont-cgroup-root`)  which it mounts into the sys container (such that cgroup-aware processes in the sys container such as systemd can further sub-cgroups without affecting the cgroups assigned to the container itself).

When sysbox creates that cgroup subtree, it's not initializing it with a value that matches the value of the parent cgroup tree (the one created by docker). As a result, even though the sysbox container is bound by the limits of the parent cgroup tree, docker stats is not picking up the right limits in the display.

I confirmed this by manually copying the value in  `/sys/fs/cgroup/docker/<container-id>/memory.limit_in_bytes` to `/sys/fs/cgroup/docker/<container-id>/syscont-cgroup-root/memory.limit_in_bytes` and after this `docker stats` shows the proper limits for the sysbox container.

Will work on a fix this week.

**Comment by ctalledo** [comment] 2021-06-14 05:19
FYI: PR for fix is here: https://github.com/nestybox/sysbox-runc/pull/44   

Will submit after code-review.

**Comment by ctalledo** [comment] 2021-06-16 16:48
PR has been merged, closing this issue.

Thanks again @sestegra for catching this!

**Closed by ctalledo** 2021-06-16 16:48 UTC
Labels: bug
