### ISSUE TITLE
Incompatibility with Docker version 20 in system container

### ISSUE THREAD

**Issue by aristipp** [nestybox/sysbox#316] opened 2021-06-13 22:28 UTC
Maybe the issue is known or i overread somthing: i have tested sysbox with Debian Buster and Ubuntu focal as host systems (running Docker version 20.10.7) and used  nestybox/ubuntu-focal-systemd:latest for testing as system container. Everything works fine with your prebuilt image and Docker version 19.03.12, but if i build the image from your Dockerfile (Docker version 20.10.7 will then also be installed in system container), i cannot launch these containers any longer:

**Examples**

httpd:2.4
`docker run -it --name apache -p 8080:80 httpd:2.4`
throws the following error:
` docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: no such file or directory: unknown.`

bitnami/apache:latest
`docker run -it --name apache bitnami/apache:latest`
throws the following error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: no such file or directory: unknown.`

Both containers work without any problems in the system container if i downgrade docker in the system container to version 19.03.12 again.

**Comment by ctalledo** [comment] 2021-06-14 00:05
Hi @aristipp , thanks for trying Sysbox!

This is a [known issue](https://github.com/nestybox/sysbox/issues/291): it's a Sysbox bug exposed by a very recent change in Docker. The issue has been fixed in the Sysbox upstream code but is not yet in packaged release (i.e., v0.3.0). We plan to release a new Sysbox package within the next couple of weeks, and it will carry this fix as well as others.

In the meantime, you can try [building Sysbox from source](https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md) (it's fairly easy as the build happens inside a container that carries all the build dependencies).

Let us know if you need any more help please. Thanks again!

**Comment by ctalledo** [comment] 2021-06-14 04:46
Closing (duplicate of issue #291).

**Closed by ctalledo** 2021-06-14 04:46 UTC
Labels: duplicate
