### ISSUE TITLE
Raising Kernel Key Retention Service variables maxbytes and maxkeys seems to be needed for high load

### ISSUE THREAD

**Issue by nudgegoonies** [nestybox/sysbox#332] opened 2021-07-06 07:13 UTC
We rolled out sysbox on 33 Gitlab Runners that all use docker-dind and every day 1-3 runners stopped working with this error:
```
starting permission container: Error response from daemon: OCI runtime create failed: container_linux.go:392: starting container process caused: process_linux.go:592: container init caused: join session keyring: create session key: disk quota exceeded: unknown (linux_set.go:105:0s)
```
After the runners reached this error everytime when the runner tried to start a new container resulting in this error a new sysboxfs mount was leaked. A restart of sysboxfs helped and removed all sysboxfs mounts and new containers could be started again.

We did't had this error before using sysbox but it seems that this can happen without sysbox as well and you can find several hints regarding the maxkeys and maxbytes variables.

First we tried raising maxkeys with "sysctl -w kernel/keys/maxkeys=1000000" which is the same value as root_maxkeys but it did not help.

After that we raised maxbytes with "sysctl -w kernel/keys/maxbytes=25000000" which is the same value as root_maxbytes as well and having both optons set helped. We havn't encountered a single error within the last 5 days.

As you can see we increased maxkeys and maxbytes to very high values. Could it be that keys are leaked by sysboxfs? At least sysboxfs mounts are leaked when this error state is reached. Or could it be that the garbace collection (gc_delay) does not run often enough? https://www.kernel.org/doc/html/v5.10/security/keys/core.html

**Comment by ctalledo** [comment] 2021-07-06 18:27
Hi @nudgegoonies, thanks for filing this issue.

For context, Sysbox allocates a session keyring each time a container is started or when the container is entered via exec (e.g., "docker exec ...") . The session keyring is destroyed when the container stops or when the "exec" exits the container. You can verify this by looking at the output of `/proc/key-users` as you create and destroy containers (i.e., you should see the key allocation count increase when the container starts, and decrease when the container stops). Note that if you are running Docker-in-Docker, inner Docker containers also add to the keyring consumption count.

Now, by default the kernel sets a low limit on the max number of keys that non-root users can have (i.e., 200). The Sysbox installer increases this limit to 20K because, on the assumption that a Sysbox-CE host machine will have ~100 containers, each using 200 keys on average (including keys used  by inner containers). 

In your case you are raising the max-keys limit to 1M keys (i.e., 50 times larger than our assumption), which sounds really large.

I don't believe however that Sysbox is leaking the keys, though I can see our test-suite is not checking exhaustively for this (something I will improve).

A couple of questions for you:

1) How many sysbox containers plus inner containers do you think are running on the host at peak time?

2) After the sysbox containers are removed, does `/proc/key-users` report that the keyrings were deallocated?

Thanks!

**Comment by nudgegoonies** [comment] 2021-07-07 07:18
Thank you very much for your explantation. I checked /proc/key-users and keys and bytes for the it is always increasing reproducible via:
- start and exit a container
- wait GC time
- the value for keys is still increased by one and the value for bytes is increased as well

I will try a master build to see if it is still the case there.

**Comment by nudgegoonies** [comment] 2021-07-07 09:36
Seems like this is already fixed in the current master!

**Comment by ctalledo** [comment] 2021-07-07 16:21
Hi @nudgegoonies,

> the value for keys is still increased by one and the value for bytes is increased as well
> ...
> Seems like this is already fixed in the current master!

mmm ... that's strange, I was under the impression we had fix this over a year ago. 

What version of Sysbox where you using when you hit the problem?

**Comment by nudgegoonies** [comment] 2021-07-07 17:14
The 0.3.0 with the journald and DeadlineExceeded commits cherry picked.

**Comment by ctalledo** [comment] 2021-07-07 23:20
> The 0.3.0 with the journald and DeadlineExceeded commits cherry picked.

I see ... thanks. 

In general, I would advice against cherry-picking specific changes, because even if the merge goes smoothly, it's possible to break functionality (e.g., the cherry-picked change may depend functionally on a prior change which was not cherry-picked). 

Also, we can't support Sysbox versions that are created by cherry-picking specific commits, because the resulting binary is not something we produced or have tested.

Glad you confirmed that things work with top-of-tree though ... sounds like this resolves the issue then.

I am closing the PR, please re-open if you feel the issue is not resolved.

Thanks as always for giving Sysbox a shot in your company's infra!

**Closed by ctalledo** 2021-07-07 23:20 UTC

**Comment by nudgegoonies** [comment] 2021-07-08 11:34
I adjusted my builds to always use the master. A release always feels better - but we use it for ci - continuous :-)
