### ISSUE TITLE
ubuntu-20.04 Can't install

### ISSUE THREAD

**Issue by little-snow-fox** [nestybox/sysbox#314] opened 2021-06-11 09:16 UTC
System info:
```
snowfox@snowfox-work:~$ cat /etc/issue
KDE neon 5.22 \n \l
snowfox@snowfox-work:~$ cat /proc/version
Linux version 5.4.0-74-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021
```
Docker status:
```
snowfox@snowfox-work:~$ docker -v
Docker version 20.10.7, build f0df350
snowfox@snowfox-work:~$ sudo service docker status
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-06-11 16:50:43 CST; 24min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 13716 (dockerd)
      Tasks: 26
     Memory: 48.3M
     CGroup: /system.slice/docker.service
             └─13716 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.039576835+08:00" level=warning msg="Your kernel does not support CPU realtime scheduler"
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.039580783+08:00" level=warning msg="Your kernel does not support cgroup blkio weight"
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.039583934+08:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.039671243+08:00" level=info msg="Loading containers: start."
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.085417485+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used >
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.103022127+08:00" level=info msg="Loading containers: done."
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.113019538+08:00" level=info msg="Docker daemon" commit=b0f5bc3 graphdriver(s)=overlay2 version=20.10.7
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.113047570+08:00" level=info msg="Daemon has completed initialization"
6月 11 16:50:43 snowfox-work systemd[1]: Started Docker Application Container Engine.
6月 11 16:50:43 snowfox-work dockerd[13716]: time="2021-06-11T16:50:43.124760115+08:00" level=info msg="API listen on /run/docker.sock"

snowfox@snowfox-work:~$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
snowfox@snowfox-work:~$ 
```

Installing:
```
snowfox@snowfox-work:~$ sudo apt-get install ./sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'sysbox-ce' instead of './sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb'
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following additional packages will be installed:
  jq libjq1 libonig5
The following NEW packages will be installed:
  jq libjq1 libonig5 sysbox-ce
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/27.1 MB of archives.
After this operation, 73.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /home/snowfox/Script/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb sysbox-ce amd64 0.3.0-0.ubuntu-focal [26.7 MB]
Preconfiguring packages ...
Selecting previously unselected package libonig5:amd64.
(Reading database ... 172040 files and directories currently installed.)
Preparing to unpack .../libonig5_6.9.4-1_amd64.deb ...
Unpacking libonig5:amd64 (6.9.4-1) ...
Selecting previously unselected package libjq1:amd64.
Preparing to unpack .../libjq1_1.6-1ubuntu0.20.04.1_amd64.deb ...
Unpacking libjq1:amd64 (1.6-1ubuntu0.20.04.1) ...
Selecting previously unselected package jq.
Preparing to unpack .../jq_1.6-1ubuntu0.20.04.1_amd64.deb ...
Unpacking jq (1.6-1ubuntu0.20.04.1) ...
Setting up libonig5:amd64 (6.9.4-1) ...
Setting up libjq1:amd64 (1.6-1ubuntu0.20.04.1) ...
Setting up jq (1.6-1ubuntu0.20.04.1) ...
(Reading database ... 172057 files and directories currently installed.)
Preparing to unpack .../sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb ...
Unsupported linux distribution: Neon 20.04
dpkg: error processing archive /home/snowfox/Script/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb (--unpack):
 new sysbox-ce package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /home/snowfox/Script/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ctalledo** [comment] 2021-06-11 13:42
Hi @little-snow-fox , thanks for trying Sysbox.

The installation fails with: `Unsupported linux distribution: Neon 20.04`;  this is because the sysbox package installer is looking for "Ubuntu 20.04".

Can you give us the output of the following on your host?

```
lsb_release -is
lsb_release -rs
```

On my Ubuntu host, I see:

```
$ lsb_release -is
Ubuntu

$ lsb_release -rs
20.04
```

Thanks!

**Comment by AMoreaux** [comment] 2021-06-11 15:45
Hi their,
Same here. I just started an ec2 instance with ubuntu 20.04. But the installation failed.
![image](https://user-images.githubusercontent.com/7237157/121713072-bac4af00-cadc-11eb-94af-beeda16295a3.png)

**Comment by ctalledo** [comment] 2021-06-11 16:01
Hi Antoine,

> Same here. I just started an ec2 instance with ubuntu 20.04. But the installation failed.

That looks to be a different problem with the same effect (can't install sysbox); what's the `sha256sum` that you see for the sysbox-ce_0.3.0 package?

```
sha256sum sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb
```

I just tried this on my host without problem:

```
$ wget https://github.com/nestybox/sysbox/releases/download/v0.3.0/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb

$ sha256sum sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb
37d300a21452e7a3201fae02bab7b2ed6bc5f571df4f99f9f2bad1895f9a0557  sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb

$ sudo apt-get install ./sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'sysbox-ce' instead of './sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb'
The following NEW packages will be installed:
  sysbox-ce
0 upgraded, 1 newly installed, 0 to remove and 103 not upgraded.
Need to get 0 B/26.7 MB of archives.
After this operation, 72.7 MB of additional disk space will be used.
Get:1 /home/cesar/downloads/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb sysbox-ce amd64 0.3.0-0.ubuntu-focal [26.7 MB]
Preconfiguring packages ...
Selecting previously unselected package sysbox-ce.
(Reading database ... 187654 files and directories currently installed.)
Preparing to unpack .../sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb ...
Unpacking sysbox-ce (0.3.0-0.ubuntu-focal) ...
Setting up sysbox-ce (0.3.0-0.ubuntu-focal) ...
Created symlink /etc/systemd/system/multi-user.target.wants/sysbox.service → /lib/systemd/system/sysbox.service.
Created symlink /etc/systemd/system/sysbox.service.wants/sysbox-fs.service → /lib/systemd/system/sysbox-fs.service.
Created symlink /etc/systemd/system/sysbox.service.wants/sysbox-mgr.service → /lib/systemd/system/sysbox-mgr.service.
```

Thanks.

**Comment by rodnymolina** [comment] 2021-06-11 17:15
@AMoreaux, we have done this process several times, but to double-check that nothing has changed I just went ahead and tried to install Sysbox in an EC2 instance and everything ran smoothly there.

As @ctalledo mentioned above I suspect that your Sysbox image was corrupted somehow.

**Comment by AMoreaux** [comment] 2021-06-11 19:37
I tried to install sysbox without downloaded the binary before 🤦‍♂️
Thanks for your quick responses.

**Comment by little-snow-fox** [comment] 2021-06-12 00:55
Thank you for helping me. 
System version:
```
snowfox@snowfox-work:~$ lsb_release -is
Neon
snowfox@snowfox-work:~$ lsb_release -rs
20.04
```

**Comment by ctalledo** [comment] 2021-06-12 03:50
Thanks @little-snow-fox . Is this a regular Ubuntu host or some variant?

How does `/etc/os-release` look like?

Here is mine:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

I ask because I want to know if we should improve / relax` the Sysbox installer's distro checking code.

Thanks!

**Comment by little-snow-fox** [comment] 2021-06-12 04:15
Ubuntu kernel, KDE interface.
System info:
```
root@snowfox-work:/opt/sysbox# cat /etc/os-release 
NAME="KDE neon"
VERSION="5.22"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.22"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by little-snow-fox** [comment] 2021-06-12 04:15
Thank you, I have successfully installed sysbox by manual compilation.

**Comment by little-snow-fox** [comment] 2021-06-12 04:19
Excuse me, docker-compose.yml configuration file, parameter '--runtime=sysbox-runc', how should I write it?

**Comment by ctalledo** [comment] 2021-06-12 16:56
Thanks @little-snow-fox; looks like your host uses the KDE Neon distro, which while it's based on Ubuntu the Sysbox installer is not  recognizing this. 

I'll check if it's possible to relax the installer's distro checking code a bit, though we can only formally support Sysbox on a limited set of distros (as otherwise the testing matrix quickly gets out of hand).

Glad you got it working by building Sysbox from source though, thanks for giving that a try.

Closing this issue now.

**Closed by ctalledo** 2021-06-12 16:56 UTC

**Comment by dr0i** [comment] 2023-01-26 16:04
Same problem  here:
```bash
$ lsb_release -is
Linuxmint
$ lsb_release -rs
20.3
```

**Comment by ctalledo** [comment] 2023-01-26 23:57
Hi @dr0i, is this with Sysbox v.0.5.2? I ask because I know we relaxed the installer checks on it ... thanks!

**Comment by dr0i** [comment] 2023-01-27 11:18
@ctalledo yes, it's sysbox-ce_0.5.2-0.linux_amd64.deb:
> Unsupported linux kernel release "5.4.0" for "{cur_distro}" distro. Sysbox may not operate as expected.

**Comment by ctalledo** [comment] 2023-01-27 17:31
> Unsupported linux kernel release "5.4.0" for "{cur_distro}" distro. Sysbox may not operate as expected.

That's a warning message we added since we don't officially support that distro (i.e., we don't test on it); did Sysbox install and does it work though?

**Comment by rodnymolina** [comment] 2023-01-30 20:44
@dr0i, this is expected behavior, as we only support kernel 5.4 in Ubuntu distro. For other distros you need at least kernel 5.5. Please see [here](https://github.com/nestybox/sysbox/blob/master/docs/distro-compat.md#supported-linux-distros) for more details.

**Comment by dr0i** [comment] 2023-01-31 09:51
@rodnymolina that's it, thx!
Regarding the error message: in some way it's explaining the cause (`"Unsupported linux kernel release "5.4.0"`), in some way it's misleading (`Sysbox may not operate as expected.` - because it's not working at all). Nice would be a message explaining what kernel is supported, or  a link to the supported kernels, or leaving out the `not operate as expected` part.

**Comment by rodnymolina** [comment] 2023-01-31 18:52
Thanks for the suggestion @dr0i, you are right, this error message needs some adjustment.
