### ISSUE TITLE
debian 12 bookworm install error

### ISSUE THREAD

**Issue by calvin2021y** [nestybox/sysbox#698] opened 2023-05-15 07:43 UTC
```sh
dpkg -i ./sysbox-ce_0.6.1-0.linux_amd64.deb 
(Reading database ... 59783 files and directories currently installed.)
Preparing to unpack .../sysbox-ce_0.6.1-0.linux_amd64.deb ...
Unpacking sysbox-ce (0.6.1.linux) over (0.6.1.linux) ...
Setting up sysbox-ce (0.6.1.linux) ...
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
```

**Comment by ctalledo** [comment] 2023-05-15 17:24
Hi @calvin2021y, thanks for trying Sysbox.

I've never seen that error before; are you running the `dpkg -i` command as sudo?

Also, try `sudo apt-get install ./sysbox-ce_0.6.1-0.linux_amd64.deb`.

**Comment by calvin2021y** [comment] 2023-05-16 04:58
I am run as root for sure.

**Comment by ctalledo** [comment] 2023-05-16 05:55
Thanks for the info; strange. 

Do you see the same error with `sudo apt-get install ./sysbox-ce_0.6.1-0.linux_amd64.deb` ?

**Comment by calvin2021y** [comment] 2023-05-16 07:01
```sh
sudo apt-get install ./sysbox-ce_0.6.1-0.linux_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'sysbox-ce' instead of './sysbox-ce_0.6.1-0.linux_amd64.deb'
The following NEW packages will be installed:
  sysbox-ce
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/11.7 MB of archives.
After this operation, 39.7 MB of additional disk space will be used.
Get:1 /root/sysbox-ce_0.6.1-0.linux_amd64.deb sysbox-ce amd64 0.6.1.linux [11.7 MB]
Selecting previously unselected package sysbox-ce.
(Reading database ... 59772 files and directories currently installed.)
Preparing to unpack .../sysbox-ce_0.6.1-0.linux_amd64.deb ...
Unpacking sysbox-ce (0.6.1.linux) ...
Setting up sysbox-ce (0.6.1.linux) ...
Created symlink /etc/systemd/system/sysbox.service.wants/sysbox-fs.service → /lib/systemd/system/sysbox-fs.service.
Created symlink /etc/systemd/system/sysbox.service.wants/sysbox-mgr.service → /lib/systemd/system/sysbox-mgr.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sysbox.service → /lib/systemd/system/sysbox.service.
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
N: Download is performed unsandboxed as root as file '/root/sysbox-ce_0.6.1-0.linux_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

**Comment by calvin2021y** [comment] 2023-05-16 15:58
one extra question, can I use sysbox-runc without sysmgr like plain `runc` ?

I try start get this error:
```sh
sudo -u web -H sysbox-runc --root=/ghost/.run run --pid-file=/ghost/.run/.pinp.pid pinp
ERRO[0000] failed to register with sysbox-mgr: failed to invoke Register via grpc: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/sysbox/sysmgr.sock: connect: no such file or directory" 
```

**Comment by ctalledo** [comment] 2023-05-16 16:13
Hi @calvin, glad `apt-get install` worked for you.

> one extra question, can I use sysbox-runc without sysmgr like plain runc ?

No, Sysbox is made up of 3 components (sysbox-runc, sysbox-mgr and sysbox-fs), and they must all be running for it to work properly. Out of curiosity, why did you ask?

**Comment by calvin2021y** [comment] 2023-05-16 16:57
`sudo apt-get install /tmp/sysbox-ce_0.6.1-0.linux_amd64.deb` throw error like `dpkg -i`, check the last line of logs.

I have a project use `crun` with custum init process,  I find some problem after `crun` upgraded.  I want find other option to replace my home med init process. that is why I ask if I can just use `sysbox-runc` replace `crun`

**Comment by ctalledo** [comment] 2023-05-16 17:08
Closing this issue now since it's resolved.

**Closed by ctalledo** 2023-05-16 17:08 UTC

**Comment by mkaatman** [comment] 2025-01-24 17:09
```
root@docker:~# sudo apt-get install ./sysbox-ce_0.6.6-0.linux_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'sysbox-ce' instead of './sysbox-ce_0.6.6-0.linux_amd64.deb'
The following NEW packages will be installed:
  sysbox-ce
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/13.3 MB of archives.
After this operation, 45.2 MB of additional disk space will be used.
Get:1 /root/sysbox-ce_0.6.6-0.linux_amd64.deb sysbox-ce amd64 0.6.6.linux [13.3 MB]
Selecting previously unselected package sysbox-ce.
(Reading database ... 22043 files and directories currently installed.)
Preparing to unpack .../sysbox-ce_0.6.6-0.linux_amd64.deb ...
Unpacking sysbox-ce (0.6.6.linux) ...
Setting up sysbox-ce (0.6.6.linux) ...
dpkg: error processing package sysbox-ce (--configure):
 installed sysbox-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 sysbox-ce
N: Download is performed unsandboxed as root as file '/root/sysbox-ce_0.6.6-0.linux_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ctalledo** [comment] 2025-01-25 13:48
Hi @mkaatman, thanks for reporting.

There are a couple of errors there:

```
dpkg: error processing package sysbox-ce (--configure):
 installed sysbox-ce package post-installation script subprocess returned error exit status 1
```

Not sure why this occurs, would need to reproduce locally to investigate. The post-installation script that is failing is here: https://github.com/nestybox/sysbox-pkgr/blob/master/deb/sysbox-ce/sysbox-ce.postinst


```
N: Download is performed unsandboxed as root as file '/root/sysbox-ce_0.6.6-0.linux_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

That error you can ignore; not quite sure why it occurs, though I believe is because `apt` uses a more restricted `__apt` behind the scenes and it has no access to `/root`. If you move the sysbox deb package to a regular user dir it may go away, not sure.
