### ISSUE TITLE
Docker --net=host fails running in sysbox

### ISSUE THREAD

**Issue by spikecurtis** [nestybox/sysbox#712] opened 2023-06-20 10:16 UTC
Starting with Docker v24.0, running `--net=host` fails if Docker is run inside a sysbox container.

I've raised a [Docker issue](https://github.com/moby/moby/issues/45681), and bisected the problem to [this Docker commit](https://github.com/moby/moby/commit/0246332954e3872995faa951d4bbe530eaac7d8f).

The outer Docker version doesn't seem to matter, and I've verified the problem on Sysbox CE 0.5.2 and 0.6.2.

The new version of Docker attempts to bind-mount `/proc/self/task/<tid>/ns/net` and this fails with "permission denied".  Curiously, if I modify the Docker code to bind-mount `/proc/thread-self/ns/net` this succeeds.  However, this is not a viable solution for Docker, because `/proc/thread-self` is unsupported on older kernels that Docker still supports.

Below is a minimal Go program that can test bind-mounting in the way Docker does:

```go
package main

import (
	"runtime"
	"fmt"
	"syscall"
	"os"
)

func main() {
	runtime.LockOSThread()
	fmt.Printf("uid: %d\n", syscall.Getuid())
	basePath := "/proc/self/task/%d/ns/net", syscall.Gettid())
	fmt.Println(basePath)
	lnPath := "/var/namespace/test"
	f, err := os.Create(lnPath)
	if err != nil {
		fmt.Printf("failed to create %s: %s\n", lnPath, err)
		os.Exit(1)
	}
	f.Close()
	err = syscall.Mount(basePath, lnPath, "bind", syscall.MS_BIND, "")
	if err != nil {
		fmt.Printf("failed to bind-mount %s: %s\n", basePath, err)
		os.Exit(1)
	}
	runtime.UnlockOSThread()
}
```

When I run it as root inside a sysbox 0.6.2 container, it fails with "permission denied."  If I switch `basePath` to be `/proc/thread-self/ns/net` it succeeds.

It also succeeds if I run it in a combination of user and mount namespaces, e.g. `unshare --user --mount --map-root-user ./bmount`.  Using `unshare` both the `/proc/self/task/<tid>` and `/proc/thread-self` variants succeed.  However, if I `unshare` with _only_ a user namespace (no mount namespace), both variants fail with permission denied.

Sysbox is the only environment I've found where `/proc/thread-self` succeeds, and `/proc/self/task/<tid>` fails.  So, something more subtle than just user namespace isolation is going on.

**Comment by rodnymolina** [comment] 2023-06-22 08:36
@spikecurtis, thanks for the detailed description, that helps.

At first glance, I don't have an explanation for what you're seeing, especially since Sysbox is doing nothing with these bind-mounts. Right, Sysbox traps mount() syscalls through seccomp-bpf but it only handles the `/proc/sys` hierarchy (as well as certain portions of `/sys`). For all other paths, Sysbox lets the kernel be the one handling the mount syscalls.

Need to think about this one in more detail.

**Comment by nudgegoonies** [comment] 2023-08-07 12:03
I can confirm for Sysbox 0.6.2, Docker 24.0.5 on Debian 11. Docker daemon on our gitlab-runner hosts and docker client within our build images is 24.0.5. Our temporary workaround is using Docker 23.0.6 for the dind rather than 24.0.5.

**Comment by anshulpatel25** [comment] 2023-09-05 01:22
I can also confirm Sysbox 0.6.2, Docker 24.0.X on Ubuntu 20.04.
We use sysbox for creating github runner pods using the Actions runner controller. We are also sticking on temporary workaround of using Docker 23.0.

**Comment by cruizba** [comment] 2023-10-25 21:06
Same here. Mentioned here, a way to replicate (https://github.com/moby/moby/issues/45681)

What is clear is that version 24 does not work with `net=host` in sysbox containers and DinD

**Comment by ctalledo** [comment] 2023-11-20 05:05
Hi @spikecurtis, thank you again for reporting this issue and your effort in helping root cause it.

The problem was a bug in the way Sysbox was intercepting mount system calls when the mount path has the form `/proc/self/task/<tid>/...`.

I've fixed it via [this commit](https://github.com/nestybox/sysbox-fs/commit/9cf74e4cbf3a61b1881bf5775460463900b55a87), so the fix will be present in the upcoming v0.6.3 release (1->2 weeks).

Closing this ticket now.

**Closed by ctalledo** 2023-11-20 05:05 UTC
Labels: bug

**Comment by vaibhav-shah** [comment] 2023-12-27 01:29
hey @ctalledo! much thanks for fixing this issue. When can we expect v0.6.3 to be released?

**Comment by ctalledo** [comment] 2024-01-02 05:36
Hi @vaibhav-shah,

> When can we expect v0.6.3 to be released?

Should be ready before the weekend, unless we hit an unforeseen problem.

**Comment by DekusDenial** [comment] 2024-01-04 01:16
> Hi @vaibhav-shah,
> 
> > When can we expect v0.6.3 to be released?
> 
> Should be ready before the weekend, unless we hit an unforeseen problem.

@ctalledo will the release cover the fix for [this issue](https://github.com/nestybox/sysbox/issues/592#issuecomment-1611783474)?

**Comment by ctalledo** [comment] 2024-01-08 20:30
Hi @DekusDenial,

> will the release cover the fix for [this issue](https://github.com/nestybox/sysbox/issues/592#issuecomment-1611783474)?

Let's discuss in that issue please to avoid polluting this one.

**Comment by ctalledo** [comment] 2024-01-10 00:19
Hi @vaibhav-shah,

> When can we expect v0.6.3 to be released?

Sysbox v0.6.3 has been released; let us know if you hit any issues please. Thanks!
