### ISSUE TITLE
Run foreign architectures via qemu-user does not work

### ISSUE THREAD

**Issue by nudgegoonies** [nestybox/sysbox#466] opened 2022-02-01 14:58 UTC
This works on docker 20.10.12 and installed qemu-user on Debian 11 but not with sysbox 0.4.1.
Plain docker:
```
❯ docker run --rm arm64v8/debian:bullseye uname -a
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
Linux 16405a02df59 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) aarch64 GNU/Linux
```
Docker with sysbox 0.4.1:
```
❯ docker run --rm arm64v8/debian:bullseye uname -a
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:323: exec user process caused: exec format error
```
Is this a bug utilizing qemu-user or does it depend on sysbox to be able to run on arm where support was started with sysbox 0.4.1?

We found this when developers wanted to build arm docker images within our gitlab-ci infrastructure.

**Comment by rodnymolina** [comment] 2022-02-01 18:20
@nudgegoonies, I'm not able to reproduce what you're seeing:

```
rmolina@dev-vm1:~$ docker run --runtime=sysbox-runc --rm arm64v8/debian:bullseye uname -a
Unable to find image 'arm64v8/debian:bullseye' locally
bullseye: Pulling from arm64v8/debian
39ab78bc09e7: Pull complete
Digest: sha256:b3d4eb0332b522963a898e4bbac06c8129ffa0f90ae8862d25313633def3f2c2
Status: Downloaded newer image for arm64v8/debian:bullseye
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
Linux 50147acda6cf 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 aarch64 GNU/Linux
```

I'm running one of the latest docker releases (20.10.12) -- please try to upgrade yours if it's not matching mine.

Also, please keep in mind the following:

* We are about to extend Sysbox support for ARM64 platforms (expected to be there in next release).
* We just implemented and merged buildx / buildkit support, but it's lacking multi-arch support, which will be implemented right after (something you may be interested on given your use-case: build arm images inside sysbox containers). Keep in mind that this will be a Sysbox-EE feature though.

**Comment by nudgegoonies** [comment] 2022-03-02 17:45
Thank you very much for your answer. Using 20.10.12 works so this issue can be closed.
But we cannot update our gitlab infrastructure to 20.10.12 because of https://github.com/nestybox/sysbox/issues/414

**Comment by rodnymolina** [comment] 2022-03-02 18:03
Understood. Will look at #414 when have a chance. Closing this issue now.

**Closed by rodnymolina** 2022-03-02 18:03 UTC
Labels: bug
