### ISSUE TITLE
Unable to create containers, "[...] failed to mkdirall [...]" | value too large for defined data type: unknown.

### ISSUE THREAD

**Issue by homeiotautomation** [nestybox/sysbox#660] opened 2023-03-24 14:41 UTC
**"value too large for defined data type: unknown."**

sudo docker run --runtime=sysbox-runc -it --rm -P --hostname=ubuntu nestybox/ubuntu-jammy-systemd-docker:latest

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: container_linux.go:425: starting container process caused: process_linux.go:607: container init caused: process_linux.go:578: handleReqOp caused: rootfs_init_linux.go:366: failed to mkdirall /var/lib/sysbox/shiftfs/0aab1eb9-d50a-43f7-81bb-084819ac3a62/var/lib/rancher/k3s: mkdir /var/lib/sysbox/shiftfs/0aab1eb9-d50a-43f7-81bb-084819ac3a62/var/lib/rancher: value too large for defined data type caused: mkdir /var/lib/sysbox/shiftfs/0aab1eb9-d50a-43f7-81bb-084819ac3a62/var/lib/rancher: value too large for defined data type: unknown.

My environment:

Proxmox
Used OS: Ubuntu server 22.04.1 LTS (Jammy Jellyfish)
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Followed the sysbox install

sudo snap remove docker
snap "docker" is not installed

Everything looks ok but cant build a container.

● sysbox.service - Sysbox container runtime
     Loaded: loaded (/lib/systemd/system/sysbox.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-24 12:56:33 UTC; 1h 51min ago
       Docs: https://github.com/nestybox/sysbox
   Main PID: 27569 (sh)
      Tasks: 2 (limit: 9402)
     Memory: 368.0K
        CPU: 24ms
     CGroup: /system.slice/sysbox.service
             ├─27569 /bin/sh -c "/usr/bin/sysbox-runc --version && /usr/bin/sysbox-mgr --version && /usr/bin/sysbox-fs --version && /bin/sleep infinity"
             └─27588 /bin/sleep infinity

Mar 24 12:56:33 quantum systemd[1]: Started Sysbox container runtime.
Mar 24 12:56:33 quantum sh[27570]: sysbox-runc
Mar 24 12:56:33 quantum sh[27570]:         edition:         Community Edition (CE)
Mar 24 12:56:33 quantum sh[27570]:         version:         0.5.2
Mar 24 12:56:33 quantum sh[27570]:         commit:         d91c42c2125fd7aaf46f66307eb5c2a025f30289
Mar 24 12:56:33 quantum sh[27570]:         built at:         Wed May 18 19:49:04 UTC 2022
Mar 24 12:56:33 quantum sh[27570]:         built by:         Rodny Molina
Mar 24 12:56:33 quantum sh[27570]:         oci-specs:         1.0.2-dev
Mar 24 12:56:33 quantum sh[27577]: sysbox-mgr
Mar 24 12:56:33 quantum sh[27577]:         edition:         Community Edition (CE)
Mar 24 12:56:33 quantum sh[27577]:         version:         0.5.2
Mar 24 12:56:33 quantum sh[27577]:         commit:         ea1b7db91031355cb10b850125e0d6502dc38962
Mar 24 12:56:33 quantum sh[27577]:         built at:         Wed May 18 19:49:36 UTC 2022
Mar 24 12:56:33 quantum sh[27577]:         built by:         Rodny Molina
Mar 24 12:56:33 quantum sh[27582]: sysbox-fs
Mar 24 12:56:33 quantum sh[27582]:         edition:         Community Edition (CE)
Mar 24 12:56:33 quantum sh[27582]:         version:         0.5.2
Mar 24 12:56:33 quantum sh[27582]:         commit:         95a773a6ea3920f7ab454f1583465c7aea4c701f
Mar 24 12:56:33 quantum sh[27582]:         built at:         Wed May 18 19:49:30 UTC 2022
Mar 24 12:56:33 quantum sh[27582]:         built by:         Rodny Molina

systemctl list-units -t service --all | grep sysbox
  sysbox-fs.service                                                                         loaded    active   running sysbox-fs (part of the Sysbox container runtime)
  sysbox-mgr.service                                                                        loaded    active   running sysbox-mgr (part of the Sysbox container runtime)
  sysbox.service                                                                            loaded    active   running Sysbox container runtime

tree /var/lib/sysbox
/var/lib/sysbox
├── buildkit
├── containerd
├── docker
├── k0s
├── kubelet
├── rancher-k3s
├── rancher-rke2
└── shiftfs

**Comment by ctalledo** [comment] 2023-03-29 01:30
Hi @homeiotautomation, this looks like a duplicate of [issue 596 (shiftfs module bug)](https://github.com/nestybox/sysbox/issues/596). 

See [this comment](https://github.com/nestybox/sysbox/issues/596#issuecomment-1291235140) for work-arounds.

**Closed** 2023-03-29 01:30 UTC
Labels: duplicate
