### ISSUE TITLE
dind-nvidia

### ISSUE THREAD

**Issue by lisenux** [nestybox/sysbox#470] opened 2022-02-08 09:54 UTC
How to use the nvidia  inside the container

**Comment by rodnymolina** [comment] 2022-02-08 16:51
@lisenux, would [this](https://github.com/nestybox/sysbox/issues/50) one meet your requirements?

If that's the case, we expect to be able to start working on this feature very soon. Could you please tell us a little bit about the use-case that you have in mind?

Thanks.

**Comment by ctalledo** [comment] 2022-03-22 23:31
Duplicate of issue #50.

**Closed by ctalledo** 2022-03-22 23:31 UTC
Labels: duplicate, question
