### ISSUE TITLE
ubuntu 24.04 release date?

### ISSUE THREAD

**Issue by antonio24073** [nestybox/sysbox#813] opened 2024-07-03 19:33 UTC
Hi,
Please Could you create images to ubuntu 24.04?
Best Regards

**Comment by ctalledo** [comment] 2024-07-10 05:25
Hi @antonio24073,

Do you mean the reference Sysbox container images? 

If so, you can easily create those by simply replacing the Ubuntu version in the associated Dockerfiles (for example [this one](https://github.com/nestybox/dockerfiles/blob/master/ubuntu-jammy-docker/Dockerfile)).

**Comment by geniass** [comment] 2024-07-25 10:03
I think the issue is that e.g. the k8s installer doesn't support Ubuntu 24.04:
```
ERROR: Sysbox is not supported on this host's distro (ubuntu-24.04).
```

I haven't been able to find the docker image definition yet so I'm not sure how easy it is to add support.

**Comment by antonio24073** [comment] 2024-07-27 21:42
actually, I managed to get 24.04 working but I thought I had to go back to 20.04 and I deleted it, now I need to do it all over again...

In my new other projects, the same thing.

it would be easier if someone just copied the Dockerfile and  tag ubuntu-noble-systemd-docker instead ubuntu-jammy-systemd-docker.  and build a image to dockerhub.

Simple!

just once instead of everyone who wants to create Dockerfile

Always when it comes to servers try to keep it up to date: a good server lives by long hops each maintenance.

The new users will want to update in 2029, not in 2027.

A detail but important.

**Comment by antonio24073** [comment] 2024-07-27 22:20
Please, if it won't bother. thank you.

**Comment by ctalledo** [comment] 2024-08-03 02:49
Hi @antonio24073, 

I've created the following images and uploaded them to Dockerhub:

```
nestybox/ubuntu-noble-docker
nestybox/ubuntu-noble-systemd
nestybox/ubuntu-noble-systemd-docker
``` 

Hope that helps!

**Comment by ctalledo** [comment] 2024-08-03 02:50
Hi @geniass,

> I think the issue is that e.g. the k8s installer doesn't support Ubuntu 24.04:
> 
> ERROR: Sysbox is not supported on this host's distro (ubuntu-24.04).

That's a separate issue, but thanks for letting us know.

**Comment by ctalledo** [comment] 2024-08-03 02:52
Closing ...

**Closed by ctalledo** 2024-08-03 02:52 UTC
