### ISSUE TITLE
k8s in docker error ls: systemd: Function not implemented

### ISSUE THREAD

**Issue by zhongcloudtian** [nestybox/sysbox#837] opened 2024-09-23 01:34 UTC
1. on k8s in docker env
![image](https://github.com/user-attachments/assets/99fd8e4b-9d61-464a-a78e-f9393cbaab33)
2. mount pod is failed
![image](https://github.com/user-attachments/assets/76dd2cee-380c-44c4-9519-a609babda27e)

**Comment by zhongcloudtian** [comment] 2024-09-23 01:37
@rodnymolina help me

**Comment by rodnymolina** [comment] 2024-09-23 05:03
@zhongcloudtian, the most common scenario in which you would see this error that you're referring to (`function not implemented`) is when one of the Sysbox daemons (either `sysbox-fs` or `sysbox-mgr`) is restarted, AND pre-existing Sysbox-powered containers/pods have kept on operating.

In other words, if sysbox daemons are restarted for whatever reason (either a manual restart or because of a sysbox bug that caused a crash/restart), then any pre-existing containers/pods launched through Sysbox must be restarted too.

During container initialization, `sysbox-fs` injects a special file-descriptor into the container operational environment. This file-descriptor is used to trap certain syscalls that are required for Sysbox's proper operation (i.e., only `mount()` and `umount()` syscall these days). This communication channel between containers/pods and Sysbox is disrupted the moment that `sysbox-fs` is restarted, so that's why you're probably seeing that error log above since the pre-existing pods are not aware of this incident; thereby, they must be manually restarted.

To confirm my point above do this:

1) Verify that Sysbox has been restarted by looking at your systemd logs with `sudo journalctl -u sysbox-mgr -u sysbox-fs`.

2) Delete and re-create the pods; you shouldn't see any issue with new instantiations of your pods.

**Comment by ctalledo** [comment] 2024-09-23 17:30
Echoing @rodnymolina comment, the `function not implemented` error occurs when the `sysbox-fs` daemon is down / not-responding for some reason.  So the sysbox-fs logs would really help.

**Comment by zhongcloudtian** [comment] 2024-09-24 00:58
--allow-trusted-xattr=false  I will  make false   issue#633
![image](https://github.com/user-attachments/assets/474982bd-999b-4ce1-9d05-6a5d2efbdfa4)

**Comment by zhongcloudtian** [comment] 2024-09-24 01:01
sysbox-fs - panic: runtime error: index out of range [0] with length 0 
issuse #633 
--allow-trusted-xattr=false

**Comment by ctalledo** [comment] 2024-10-09 21:06
Thanks @zhongcloudtian.

Should be fixed by [this PR](https://github.com/nestybox/sysbox-fs/pull/97), which will be present in the upcoming release.

Thanks!

**Comment by ctalledo** [comment] 2024-10-09 21:07
Closing as duplicate of #633 .

**Closed by ctalledo** 2024-10-09 21:07 UTC
Labels: duplicate
