### ISSUE TITLE
The container inside the sysbox with the published ports does not start if the sysbox has /var/lib/docker mounted

### ISSUE THREAD

**Issue by dmalapsh** [nestybox/sysbox#758] opened 2023-12-26 16:25 UTC
Steps:

1. Mount /var/lib/docker as specified [here](https://github.com/nestybox/sysbox/blob/master/docs/quickstart/dind.md#persistence-of-inner-container-images-using-docker-volumes) and run
2. Run docker-compose inside a container
``` 
...
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
...
```
3. Stop and remove the root container
4. Repeat steps 1 and 2 using the same data
The error I'm getting is:
```
docker-compose up
<...>
Error response from daemon: driver failed programming external connectivity on endpoint project-nginx-1 (bb343fe6db5bcd4f3ee9bca047060f61de847e1ca7498f68c003a0efad3b86ca): Bind for 0.0.0.0:80 failed: port is already allocated
```
Features that have been noticed:
- The port is occupied by the docker-proxy process.
- At the same time, containers that do not have public ports are launched successfully when the root container is started
- If you run `docker-compose stop` inside the container before performing step 3, then all docker-compose containers will start automatically

**Comment by ctalledo** [comment] 2024-01-02 05:35
Hi @dmalapsh,

Thanks for giving Sysbox a shot and reporting the issue.

Based on the description above, sounds like this is a not a problem in Sysbox per-se, but rather a problem caused by `docker-compose up` leaving some stale state under the mounted `/var/lib/docker`. Therefore, when the Sysbox container is stopped and later re-created, re-running `docker-compose up` fails because it must not be finding clean state under `/var/lib/docker`. It's likely equivalent to running `docker-compose up` twice without a `docker-compose stop` in between. 

> If you run docker-compose stop inside the container before performing step 3, then all docker-compose containers will start automatically

That makes sense to me, as the `docker-compose stop` must be cleaning up any stale state stored under the mounted `/var/lib/docker`. 

I am pretty confident the problem won't occur if you follow the steps you described but without mounting `/var/lib/docker`, since the Sysbox container will start with a clean `/var/lib/docker` every time.

Does this make sense? In my view it's behaving the way it should, and sounds like you need a `docker-compose stop` before stopping the Sysbox container, or right after you recreate it.

**Comment by dmalapsh** [comment] 2024-01-02 22:31
Hi @ctalledo, 
You are right, if `/var/lib/docker` is not mounted, then there is no problem.
However, I need to keep the state in order not to create unnecessary load. At the same time, I cannot perform a docker-compose stop before stopping the container, since this happens automatically and I cannot influence it. If you execute the command after re-creation, it will have no effect, because docker-compose is not considered running.
Perhaps it is worth mounting not the entire` /var/lib/docker folder`?

**Comment by ctalledo** [comment] 2024-01-13 20:52
> At the same time, I cannot perform a docker-compose stop before stopping the container, since this happens automatically and I cannot influence it.

Hi @dmalapsh, sorry for the belated reply.

> Perhaps it is worth mounting not the entire `/var/lib/docker` folder?

No that's not a good idea, because as a user you wouldn't know what portions of it to mount or not. Plus it could change on a new release of Docker or docker-compose. 

How about running `docker-compose stop` (or a similar cleanup command) when the container starts, as a way of cleaning up any unclean state left in `/var/lib/docker`?

**Comment by dmalapsh** [comment] 2024-01-24 12:21
Running commands after starting the container does not help. docker thinks that nothing is running. However, when calling the `docker network ls` command, I see
```b5713ed2d952   none      null      local```
After that, I run `docker network rm b5713ed2d952` and get `Error response from daemon: none is a pre-defined network and cannot be removed`

**Comment by ctalledo** [comment] 2024-01-30 03:22
> Running commands after starting the container does not help.

Meaning that running `docker-compose stop` when the container starts does not do anything? 

> After that, I run docker network rm b5713ed2d952 and get Error response from daemon: none is a pre-defined network and cannot be removed

Yes that's expected Docker behavior because the predefined network `none`, `host`, and `bridge` are not removable. 

But why did you try to remove the networks? As part of cleaning up Docker start manually when the container starts?

**Comment by dmalapsh** [comment] 2024-02-06 09:25
Sorry for misleading you, docker-compose stop stops containers that were able to start (containers using the network could not start initially). However, this does not help and docker-compose up still throws an error. I thought that the none network was exactly the network that had not ended since the last launch. Now I realized that this is the default network

**Comment by ctalledo** [comment] 2024-02-15 04:29
Hi @dmalapsh, 

I still find it strange that using `docker-compose stop` as a cleanup step when restarting the Sysbox container does not work well, given that you indicated that if you run it before stopping the Sysbox container then things work fine

> If you run docker-compose stop inside the container before performing step 3, then all docker-compose containers will start automatically

In any case, I hope you find a solution; as I mentioned earlier, this is not a problem in Sysbox per-se, but rather an issue of cleaning up state that is persisted by the container across restarts (via the bind-mount on `/var/lib/docker`).

Thus, I'll close this issue (it's not a bug in Sysbox), but nonetheless we can continue the conversation to see if we can find a solution.

**Closed by ctalledo** 2024-02-15 04:29 UTC
Labels: question
