### ISSUE TITLE
Git submodule doesn't exist for sysbox-staging

### ISSUE THREAD

**Issue by myugan** [nestybox/sysbox#75] opened 2020-09-28 06:47 UTC
Hi @rodnymolina 

I want to inform for the missing submodule, since I have an issue from the latest version then I try with version `v0.2.0` it seems the repository doesn't exist for this one https://github.com/nestybox/sysbox-staging/tree/57a8bba69aecba9c1906d366216bf1c9642b7a05

**Comment by ctalledo** [comment] 2020-09-28 17:26
Hi @myugan, thanks for filing the issue.

> since I have an issue from the latest version

What issue where you having with the latest version?

>  I try with version v0.2.0 it seems the repository doesn't exist

What procedure did you use when you hit the error? (I am not able to reproduce it on my side).

In general though, I would stick with the latest release since it always has the latest features and fixes, etc.

**Comment by myugan** [comment] 2020-09-28 17:29
The previous issue is https://github.com/nestybox/sysbox/issues/73

**Comment by ctalledo** [comment] 2020-09-28 22:41
> The previous issue is #73

I see, thanks. That issue should be mostly cosmetic though as described by @rodnymolina [here](https://github.com/nestybox/sysbox/issues/73#issuecomment-699044168). I would still recommend you use the latest version since it has our latest fixes. 

Coming back to this current issue, what procedure did you use when you hit the error? (I am not able to reproduce it on my side).

**Comment by myugan** [comment] 2020-09-29 03:57
As usual i clone the repo with specific branch name and do `git submodule update --recursive` then the output say repository doesn't exist

**Comment by ctalledo** [comment] 2020-09-29 04:37
Thanks @myugan. I am not seeing the exact same error, in that the following command worked for me:

```
git clone --branch v0.2.0 --recurse-submodules  git@github.com:nestybox/sysbox.git
```

But if I then try to build from source, I do hit another error:

```
cesar@eoan:~/sysbox-tmp/sysbox$ make sysbox                                 
Building libseccomp ...                                                                                                                                        
bash: line 0: cd: lib/seccomp: No such file or directory
make: *** [Makefile:130: lib/seccomp/src/.libs/libseccomp.a] Error 1    
```

Looks like the v0.2.0 branch repo is not quite right then (we are missing some dependencies). Rather than going back, let's continue on v0.2.1 since the problem is not present in that repo.

Let's continue the discussion on issue #73 and close this one.

**Closed by ctalledo** 2020-09-29 04:37 UTC
