### ISSUE TITLE
Unexpected error during NotifReceive() execution

### ISSUE THREAD

**Issue by myugan** [nestybox/sysbox#169] opened 2020-12-28 08:43 UTC
Hi @ctalledo @rodnymolina 

I have an error log like this, i'm not sure because of this our containers sometimes crash can't kill the running containers without restart the docker daemon.

```
WARN[2020-12-23 05:30:53] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 26 pid 22364
WARN[2020-12-23 07:28:28] sysbox-fs caught signal: terminated
WARN[2020-12-23 12:55:42] sysbox-fs caught signal: terminated
WARN[2020-12-23 16:09:01] Error decoding received nsenterMsg response: read nsenterPipe-p: connection reset by peer
WARN[2020-12-23 16:18:02] Sysbox-fs first child process error status: pid = 6723
WARN[2020-12-23 16:18:02] Sysbox-fs first child process error status: pid = 6722
WARN[2020-12-23 21:50:24] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 14 pid 29780
WARN[2020-12-24 10:35:02] Error decoding received nsenterMsg response: read nsenterPipe-p: connection reset by peer
WARN[2020-12-24 18:57:02] Error decoding received nsenterMsg response: read nsenterPipe-p: connection reset by peer
WARN[2020-12-25 14:14:44] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 30 pid 3068
WARN[2020-12-25 15:58:03] Error decoding received nsenterMsg response: read nsenterPipe-p: connection reset by peer
WARN[2020-12-25 22:36:04] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 29 pid 6920
WARN[2020-12-26 01:39:33] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 190 pid 25454
WARN[2020-12-26 09:39:34] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 156 pid 26159
WARN[2020-12-26 13:50:29] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 77 pid 17239
WARN[2020-12-26 19:15:10] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 78 pid 21232
WARN[2020-12-26 21:25:06] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 87 pid 23710
WARN[2020-12-27 00:35:03] Unexpected error during NotifReceive() execution (bad file descriptor) on fd 53 pid 6342
WARN[2020-12-27 01:48:35] Unexpected error during NotifReceive() execution (inappropriate ioctl for device) on fd 168 pid 7878
WARN[2020-12-27 07:14:40] Unexpected error during NotifReceive() execution (bad file descriptor) on fd 43 pid 30142
```

**Comment by rodnymolina** [comment] 2020-12-28 17:04
@myugan, we fixed an [issue](https://github.com/nestybox/sysbox-fs/pull/15) a few weeks ago that would explain what you describe above. Can you please try with our latest code by building from sources?

**Comment by myugan** [comment] 2020-12-28 17:06
Okay got it, is it possible to create deb package for the latest update instead of compiling from the source.

**Comment by rodnymolina** [comment] 2020-12-28 17:15
At the moment you cannot create deb images by your own. However, we are about to start our next release cycle, so we are expecting to have the new images ready soon (one or two weeks).

**Comment by rodnymolina** [comment] 2021-01-05 02:54
As explained above, problem has been already fixed in top-of-tree. Please let us know if have any other question on this matter. Will close this one now.

**Closed by rodnymolina** 2021-01-05 02:54 UTC
Labels: bug, duplicate

**Comment by myugan** [comment] 2021-01-07 04:23
I want to ask, there is any possibility the docker container with `dead` state is caused by `sysbox`?

**Comment by ctalledo** [comment] 2021-01-07 05:39
Hi @myugan:

> I want to ask, there is any possibility the docker container with dead state is caused by sysbox?

I've never come across that. In what context are you seeing this?

**Comment by myugan** [comment] 2021-01-07 07:19
I'm not sure about this but some time in our system there is a container stuck and need to restart the daemon, when I see the process with `docker ps` it turns to `dead` state

**Comment by ctalledo** [comment] 2021-01-07 18:37
> I'm not sure about this but some time in our system there is a container stuck and need to restart the daemon, when I see the process with `docker ps -a` it turns to `dead` state

Got it.  The error you reported above could lead to a container getting stuck / hanged. 

As @rodnymolina mentioned, this error should be fixed in Sysbox top-of-tree. Have you seen this error with the Sysbox top-of-tree?

**Comment by myugan** [comment] 2021-01-08 03:47
Ah okay, so that's the case because I still use the latest update deb package in Ubuntu and still waiting a new latest update as @rodnymolina told me. Thanks in advance

**Comment by myugan** [comment] 2021-01-17 09:04
<img width="840" alt="image" src="https://user-images.githubusercontent.com/20453528/104836051-74787480-58dd-11eb-9719-06aee5d5ac82.png">

This is related to sysbox? like i said before, the docker is stuck sometimes when i remove the container.

cc @rodnymolina @ctalledo

**Comment by ctalledo** [comment] 2021-01-18 03:25
Hi @myugan: 

> This is related to sysbox? like i said before, the docker is stuck sometimes when i remove the container.

Need more info to help you here.

What process is that strace from? 

I suspect it's the docker CLI (since it's trying to open `/var/run/docker.sock`).  I don't see how Sysbox could have any effect on the Docker CLI communicating with the daemon.

**Comment by myugan** [comment] 2021-01-24 00:14
Hi @ctalledo seems this is not coming again, you're right this issue doesn't come from sysbox itself but another configuration in docker that leads to `stdout being buffered` so its turn the container stuck.

**Comment by ctalledo** [comment] 2021-01-24 17:36
> Hi @ctalledo seems this is not coming again, you're right this issue doesn't come from sysbox itself but another configuration in docker that leads to `stdout being buffered` so its turn the container stuck.

Thanks @myugan for root causing and confirming that it's not a Sysbox related issue, much appreciated.

**Comment by myugan** [comment] 2021-02-28 07:16
Hi @ctalledo 

Now I have the same issue but this is not coming from the Docker configuration, these things only happen sometimes that causes the container in **Created** state for a minute then the container can running (**Up** state)

```
Unexpected error during NotifReceive() execution (bad file descriptor) on fd
```

**Comment by ctalledo** [comment] 2021-02-28 17:44
Thanks @myugan for the update. 

Is this behavior reproducible? If so, what are the steps to reproduce it?

The `Unexpected error during NotifReceive() execution` warning is usually not a problem, it sometimes occurs when a process inside a container performs an system call trapped by Sysbox (e.g., mount syscall, etc) but then dies unexpectedly (usually because the container associated with that process was stopped).

Thanks as always for reporting.

**Comment by myugan** [comment] 2021-02-28 17:50
Unfortunately, this is not reproducible at the moment but I will let you know once I can find a way how to get this issue consistently.
