### ISSUE TITLE
Sysbox fail to recognize shiftfs on debian stable

### ISSUE THREAD

**Issue by janLo** [nestybox/sysbox#679] opened 2023-04-20 13:54 UTC
I'm running sysbox with docker on a debain stable system (11.6). Shiftfs is installed via DKMS and worked well so far (with sysbox 0.5.2).

After an upgrade to 0.6.1 the sysbox-mgr reports that sysbox is not working properly and disables it, rendering the whole installation unusable. 

I've tracked the problem down to [this mount](https://github.com/nestybox/sysbox-libs/blob/a85081b6a478be10cea2252837cc6dea643d1a46/shiftfs/shiftfs.go#L169), which returns with an `EACCESS`:

```
10:59:22.443563 mount("/var/lib/sysbox/sysbox-shiftfs-check3832227125/test", "/var/lib/sysbox/sysbox-shiftfs-check3832227125/test", "shiftfs", 0, NULL) = -1 EACCES (Permission denied)
```

Strangely, this ONLY happens if the sysbox-mgr is started via Systemd. If started manually, the mount works fine and Shiftfs is reported as working properly:

```
root@ws-6:~# systemctl restart sysbox-mgr && sleep 3 && journalctl -n 12 -u sysbox-mgr | grep Shiftfs
Apr 19 09:24:20 ws-6 sysbox-mgr[3624148]: time="2023-04-19 09:24:20" level=info msg="Shiftfs module found in kernel: yes"
Apr 19 09:24:20 ws-6 sysbox-mgr[3624148]: time="2023-04-19 09:24:20" level=info msg="Shiftfs works properly: no"
Apr 19 09:24:20 ws-6 sysbox-mgr[3624148]: time="2023-04-19 09:24:20" level=info msg="Shiftfs-on-overlayfs works properly: no"
root@ws-6:~# systemctl stop sysbox-mgr
root@ws-6:~# sysbox-mgr 2>&1 | grep Shiftfs
time="2023-04-19 09:25:07" level=info msg="Shiftfs module found in kernel: yes"
time="2023-04-19 09:25:07" level=info msg="Shiftfs works properly: yes"
time="2023-04-19 09:25:07" level=info msg="Shiftfs-on-overlayfs works properly: yes"
```

The system is a standard debian installation. The systemd units for sysbox are the ones the package provides.

```
root@ws-6:~# uname -a
Linux ws-6 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
systemd:
  Installed: 247.3-7+deb11u1
  Candidate: 247.3-7+deb11u1
  Version table:
     252.5-2~bpo11+1 100
        100 http://mirror/debian bullseye-backports/main amd64 Packages
 *** 247.3-7+deb11u1 500
        500 http://mirror/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
root@ws-6:~# apt-cache policy sysbox-ce
sysbox-ce:
  Installed: 0.6.1.linux
  Candidate: 0.6.1.linux
  Version table:
 *** 0.6.1.linux 100
        100 /var/lib/dpkg/status
root@ws-6:~# modinfo shiftfs
filename:       /lib/modules/5.10.0-20-amd64/updates/dkms/shiftfs.ko
license:        GPL v2
description:    id shifting filesystem
author:         Christian Brauner <christian.brauner@ubuntu.com>
author:         Seth Forshee <seth.forshee@canonical.com>
author:         James Bottomley
alias:          fs-shiftfs
depends:        
retpoline:      Y
name:           shiftfs
vermagic:       5.10.0-20-amd64 SMP mod_unload modversions 
```

I still cannot understand why this happens in a systemd context and only there. The capability sets the processes have been the same, no matter how they got started. I can only imagine some default seccomp policy or similar things Systemd might set for the process, but I wasn't able to track it down.

As shiftfs generally works (with 0.5.2) I would ask if it would be possible to have a command line flag to disable the check (or force-enable shiftfs).

**Comment by rodnymolina** [comment] 2023-04-20 17:48
@janlo, thanks for the detailed description.

At first glance I have no explanation for the difference you are observing between the "systemd" vs "no-systemd" initialization approach. This is something that we would have seen in our pre-release testing, so as you said, I suspect this has something to do with your "debian" machine and a lower-level config/kernel attribute setting (we usually do most testing with Ubuntu). We will need to reproduce this behavior locally to tell.

Moving away from the "systemd" discrepancy, I have one question for you: can you confirm that in this same debian machine, without making any upgrades/downgrades of any packages, and with the same shiftfs kernel module, you are able to run Sysbox v0.5.2 successfully? This would be something unexpected for me and would be an indication that we may have a bug in our recently introduced "shiftfs-testing" logic, which is the one that fails with the EPERM you dumped above.

**Comment by janLo** [comment] 2023-04-20 20:19
Hello @rodnymolina, The installation is pretty standard (what the installer leaves plus docker and some telemetry, no changes to the kernel commandline or systemd). Its also reproducible over all our machines.

I can confirm that 0.5.2 worked before the upgrade to 0.6.1. I downgraded to 0.5.2 again and it worked again.

**Comment by ctalledo** [comment] 2023-04-20 22:21
Thanks @janLo; we wil try to repro on a machine with a working shiftfs.

**Comment by fallobst22** [comment] 2023-04-25 09:14
Hello!

I encountered this issue as well and can confirm the described behavior.
I was able to reproduce the issue on AWS using the latest provided image of Debian at the time of writing (ami-08f13e5792295e1b2),  Perhaps this information will be useful.

**Comment by ctalledo** [comment] 2023-05-01 23:06
We still have to root cause this but as a work-around we've added a flag called "--disable-shiftfs-precheck" in sysbox-mgr to bypass this problem. The [commit](https://github.com/nestybox/sysbox-mgr/commit/12c1d52e12c61a631c61a6be20b43c71f14c6641) has been merged into the master branch but it's not yet released. 

The next release (likely in a few weeks as we collect other fixes) will contain this fix.

In the meantime, you can [build the Sysbox binaries from source](https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md#sysbox-developers-guide-building--installing) if you need it earlier.

**Comment by ctalledo** [comment] 2023-05-04 00:04
Hi @janLo, I was able to repro on a Debian 11 host. That's half the battle. I'll debug it and get back to you.

**Comment by ctalledo** [comment] 2023-05-04 05:58
Found the root cause, fix PR is here: https://github.com/nestybox/sysbox-mgr/pull/65

**Closed** 2023-05-05 00:49 UTC
Labels: bug
