### ISSUE TITLE
Support for k8s version 1.25?

### ISSUE THREAD

**Issue by vyas-n** [nestybox/sysbox#611] opened 2022-12-08 16:46 UTC
I tried to install sysbox on my k0s cluster and it started crash looping:
```
❯ kubectl get pod -n kube-system | grep sysbox
sysbox-deploy-k8s-8htgx                    0/1     CrashLoopBackOff   6 (51s ago)   6m53s
sysbox-deploy-k8s-nghld                    0/1     CrashLoopBackOff   6 (65s ago)   6m53s
```

When I checked the logs it said k8s version 1.25 is not supported:
```
❯ kubectl logs daemonset.apps/sysbox-deploy-k8s -n kube-system
Found 2 pods, using pod/sysbox-deploy-k8s-8htgx
ERROR: Sysbox is not supported on this Kubernetes version (v1.25).
```

Is there a blocking factor in supporting v1.25?

**Comment by ctalledo** [comment] 2022-12-08 18:24
Hi @vyas-n, we don't yet support installing Sysbox on K0s unfortunately. See [issue #606]( https://github.com/nestybox/sysbox/issues/606).

**Comment by ctalledo** [comment] 2022-12-08 18:24
Closing as duplicate of Issue #606.

**Closed by ctalledo** 2022-12-08 18:24 UTC

**Comment by vyas-n** [comment] 2022-12-08 19:56
Hi @ctalledo,

Thanks for letting me know. Just to confirm, k8s v1.25 is supported on sysbox? Just not k0s?

**Comment by ctalledo** [comment] 2023-03-29 00:40
> Thanks for letting me know. Just to confirm, k8s v1.25 is supported on sysbox? Just not k0s?

Apologies for the super belated reply, but better late than never: K8s v1.25 is about to be supported on Sysbox, but K0s is not supported at all right now.
