### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by punitporwal07** [nestybox/sysbox#782] opened 2024-02-26 17:07 UTC
Dear Team,

After setting up sysbox by following the [guide](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md)   on Ubuntu v20.04 with upgraded kernel 5.10.0-051000-generic, I am still not able to get container run-time.

while running docker ps inside the container it is reporting docker daemon not running.

can you please suggest, how to fix this issue, or what can be checked here? 

k/r
Punit

**Comment by ctalledo** [comment] 2024-02-28 03:51
Hi @punitporwal07,

Thanks for trying Sysbox.

> I am still not able to get container run-time.
> while running docker ps inside the container it is reporting docker daemon not running.

So we can help you further, please provide the exact command you are using and outputs you see when:

1) Starting the sysbox container
2) Starting or using Docker inside the Sysbox container

Thanks!

**Comment by punitporwal07** [comment] 2024-02-29 10:08
it appears to me that, the sysbox is running as expected (big thanks to sysbox community), there seems to be an issue with the image I am using, may be first I need to check if I can run this jenkins-agent image locally to check if it is picking up the sysbox runtime env or not.

**Comment by KarstenVogt** [comment] 2024-06-21 07:27
Hello,

I'm experiencing the same problems with this project.

###Docker engine info
``
 root on ultracool at 󰋜 ~ docker info
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 3
  Paused: 0
  Stopped: 5
 Images: 11
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: loki
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: sysbox-runc io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-35-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.5GiB
 Name: ultracool
 ID: 6d894c0d-3ac1-44f1-99ce-f394b18551a7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 53
  Goroutines: 72
  System Time: 2024-06-21T09:19:49.719005592+02:00
  EventsListeners: 0
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
``

###Sysbox info
``
 root on ultracool at 󰋜 ~ sysbox-mgr --version
sysbox-mgr
        edition:        Community Edition (CE)
        version:        0.6.4
        commit:         03f5d7bc584fdcb2319b2c1831bd58581185fc1c
        built at:       Sat Apr  6 16:43:43 UTC 2024
        built by:       Cesar Talledo
``

###Run Nestybox image:
`` root on ultracool at …/docker docker run --runtime=sysbox-runc --rm -it nestybox/ubuntu-jammy-docker:latest
``

###In container
``
root@37e9235ac7b4:/# docker --version
Docker version 20.10.17, build 100c701
root@37e9235ac7b4:/# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
``

**Comment by KarstenVogt** [comment] 2024-06-24 11:49
I had the same issue. This link helped a lot: https://github.com/nestybox/sysbox/issues/784

**Comment by ctalledo** [comment] 2024-07-10 04:57
Closing as duplicate of #784.

**Closed by ctalledo** 2024-07-10 04:57 UTC
