### ISSUE TITLE
Sysbox release not available for Download

### ISSUE THREAD

**Issue by achimcc** [nestybox/sysbox#585] opened 2022-08-16 08:28 UTC
Hello, 

I'm currently trying to download the latest sysbox binary from here: https://downloads.nestybox.com/sysbox/releases/v0.5.2/sysbox-ce_0.5.2-0.linux_amd64.deb

`wget` gives me a 403, Forbidden...

**Comment by devalpatel67** [comment] 2022-08-16 15:27
I am facing the same issue. It's the same for version v0.5.0.

**Comment by devalpatel67** [comment] 2022-08-16 18:39
It seems like solved.

**Comment by rodnymolina** [comment] 2022-08-16 19:29
@achimcc, @devalpatel67, thanks for reporting this issue. The problem is fixed now.

**Closed by rodnymolina** 2022-08-16 19:29 UTC
